##===- lib/Target/`'__arch__`'/Makefile ----------------------------*- Makefile -*-===##
#
#                     The ArchC LLVM Backend Generator
#
##===----------------------------------------------------------------------===##
LEVEL = ../../..
LIBRARYNAME = LLVM`'__arch__`'
TARGET = `'__arch__`'

# Make sure that tblgen is run, first thing.
BUILT_SOURCES = __arch__`'GenRegisterInfo.h.inc __arch__`'GenRegisterNames.inc \
                __arch__`'GenRegisterInfo.inc __arch__`'GenInstrNames.inc \
                __arch__`'GenInstrInfo.inc __arch__`'GenAsmWriter.inc \
                __arch__`'GenDAGISel.inc __arch__`'GenCallingConv.inc \
                __arch__`'GenSubtarget.inc

include $(LEVEL)/Makefile.common

