//=====-- __arch__`'Subtarget.h - Define Subtarget for the __arch_in_caps__ ----*- C++ -*-====//
//
//                     The ArchC LLVM Backend Generator
//
//   This file was automatically generated from an ArchC description.
//
//===----------------------------------------------------------------------===//
//
// This file declares the __arch_in_caps__ specific subclass of TargetSubtarget.
//
//===----------------------------------------------------------------------===//

`#ifndef '__arch_in_caps__`_SUBTARGET_H'
`#define '__arch_in_caps__`_SUBTARGET_H'

#include "llvm/Target/TargetSubtarget.h"
#include <string>

namespace llvm {
  class Module;
  
class __arch__`'Subtarget : public TargetSubtarget {
  bool IsV9;
public:
  __arch__`'Subtarget(const Module &M, const std::string &FS);

  bool isV9() const { return IsV9; }

  /// ParseSubtargetFeatures - Parses features string setting specified 
  /// subtarget options.  Definition of function is auto generated by tblgen.
  void ParseSubtargetFeatures(const std::string &FS, const std::string &CPU);
  
};

} // end namespace llvm

#endif
